# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameter.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_Child(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(801, 245)
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(50, 60, 331, 29))
        self.horizontalSlider.setMouseTracking(False)
        self.horizontalSlider.setAcceptDrops(False)
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setMinimum(-64)
        self.horizontalSlider.setMaximum(64)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(50, 110, 331, 29))
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setProperty("value", 50)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(50, 160, 331, 29))
        self.horizontalSlider_3.setMaximum(128)
        self.horizontalSlider_3.setProperty("value", 64)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_4 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(50, 210, 331, 29))
        self.horizontalSlider_4.setMinimum(100)
        self.horizontalSlider_4.setMaximum(500)
        self.horizontalSlider_4.setProperty("value", 300)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalSlider_5 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(450, 60, 331, 29))
        self.horizontalSlider_5.setMinimum(-180)
        self.horizontalSlider_5.setMaximum(180)
        self.horizontalSlider_5.setProperty("value", 0)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.horizontalSlider_6 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(450, 210, 331, 29))
        self.horizontalSlider_6.setMinimum(2800)
        self.horizontalSlider_6.setMaximum(6500)
        self.horizontalSlider_6.setProperty("value", 4600)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.horizontalSlider_7 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(450, 110, 331, 29))
        self.horizontalSlider_7.setMinimum(-100)
        self.horizontalSlider_7.setMaximum(100)
        self.horizontalSlider_7.setProperty("value", 64)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.horizontalSlider_8 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_8.setGeometry(QtCore.QRect(450, 160, 331, 29))
        self.horizontalSlider_8.setMaximum(100)
        self.horizontalSlider_8.setProperty("value", 50)
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName("horizontalSlider_8")
        self.horizontalSlider_9 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_9.setGeometry(QtCore.QRect(450, 20, 331, 20))
        self.horizontalSlider_9.setMaximum(10000)
        self.horizontalSlider_9.setProperty("value", 156)
        self.horizontalSlider_9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_9.setObjectName("horizontalSlider_9")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(14, 60, 31, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 110, 51, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(13, 160, 31, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(0, 210, 51, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(380, 20, 61, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(410, 60, 31, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(396, 110, 51, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(410, 160, 31, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(395, 210, 51, 20))
        self.label_9.setObjectName("label_9")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(230, 20, 96, 25))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(60, 17, 95, 30))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "参数设置"))
        self.label.setText(_translate("Dialog", "亮度"))
        self.label_2.setText(_translate("Dialog", "对比度"))
        self.label_3.setText(_translate("Dialog", "增益"))
        self.label_4.setText(_translate("Dialog", "Gamma"))
        self.label_5.setText(_translate("Dialog", "曝光时间"))
        self.label_6.setText(_translate("Dialog", "色度"))
        self.label_7.setText(_translate("Dialog", "饱和度"))
        self.label_8.setText(_translate("Dialog", "锐化"))
        self.label_9.setText(_translate("Dialog", "白平衡"))
        self.checkBox.setText(_translate("Dialog", "自动曝光"))
        self.pushButton.setText(_translate("Dialog", "恢复初始参数"))

